// Identificadores de los logros que existen. Lo usa la API para aceptar solo logros del catálogo (sin
// dependencias de la app: el servidor no puede importar src/data). Una prueba comprueba que esta lista
// y el catálogo de la app (src/data/achievements.ts) sean exactamente los mismos.
export const ACHIEVEMENT_IDS: readonly string[] = [
  'first-signal',
  'burst-starter',
  'quiz-bronze',
  'career-explorer',
  'route-complete',
  'temple-restored',
  'route-podium',
  'route-champion',
  'station-explorer',
  'streak-three',
  'security-guard',
  'perfect-run',
  'level-five',
  'signal-restored',
  'net-architect',
  'binary-brain',
  'code-breaker',
  'daily-three',
  'memory-ace',
  'puzzle-fan',
  'all-rounder',
  'burst-flawless',
  'daily-seven',
  'runner-rookie',
  'runner-courier',
  'data-collector',
  'burst-master',
  'burst-collector',
  'rutix-friend',
  'quiz-master',
  'level-ten',
];
